// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActiveSkill struct {
	ID          int64
	DisplayName pgtype.Text
	Description pgtype.Text
	Types       []string
	EmbeddingID pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Embedding struct {
	ID        int64
	Embedding pgvector.Vector
}
