// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createActiveSkill = `-- name: CreateActiveSkill :one
INSERT INTO active_skills (
  display_name,
  description,
  types,
  embedding_id
) VALUES (
  $1::text,
  $2::text,
  $3,
  $4::bigint
)
RETURNING
  id
`

type CreateActiveSkillParams struct {
	DisplayName string
	Description string
	Types       []string
	EmbeddingID int64
}

func (q *Queries) CreateActiveSkill(ctx context.Context, arg CreateActiveSkillParams) (int64, error) {
	row := q.db.QueryRow(ctx, createActiveSkill,
		arg.DisplayName,
		arg.Description,
		arg.Types,
		arg.EmbeddingID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createEmbedding = `-- name: CreateEmbedding :one
INSERT INTO embeddings (
  embedding
) VALUES (
  $1::vector(3072)
)
RETURNING
  id
`

func (q *Queries) CreateEmbedding(ctx context.Context, embedding pgvector.Vector) (int64, error) {
	row := q.db.QueryRow(ctx, createEmbedding, embedding)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMostSimilarActiveSkill = `-- name: GetMostSimilarActiveSkill :one
SELECT
  a.id,
  a.display_name,
  a.description,
  a.types
FROM active_skills a
JOIN embeddings e ON e.id = a.embedding_id
WHERE a.embedding_id IS NOT NULL
ORDER BY e.embedding <-> $1::vector(3072)
LIMIT 1
`

type GetMostSimilarActiveSkillRow struct {
	ID          int64
	DisplayName pgtype.Text
	Description pgtype.Text
	Types       []string
}

func (q *Queries) GetMostSimilarActiveSkill(ctx context.Context, queryEmbedding pgvector.Vector) (GetMostSimilarActiveSkillRow, error) {
	row := q.db.QueryRow(ctx, getMostSimilarActiveSkill, queryEmbedding)
	var i GetMostSimilarActiveSkillRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Description,
		&i.Types,
	)
	return i, err
}
